import * as p from '@clack/prompts';
import { execSync } from 'child_process';
import { existsSync, copyFileSync, writeFileSync, readFileSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

const HOME = homedir();
const DEST = join(HOME, '.tmux.conf');

// Detect clipboard
let COPY_CMD = 'pbcopy';
let PASTE_CMD = 'pbpaste';
if (process.platform === 'linux') {
    try { execSync('which xclip', { stdio: 'ignore' }); COPY_CMD = 'xclip -selection clipboard'; PASTE_CMD = 'xclip -selection clipboard -o'; }
    catch { try { execSync('which xsel', { stdio: 'ignore' }); COPY_CMD = 'xsel --clipboard --input'; PASTE_CMD = 'xsel --clipboard --output'; }
    catch { COPY_CMD = ''; PASTE_CMD = ''; } }
}

// Check tmux
let tmuxVersion = '';
try { tmuxVersion = execSync('tmux -V', { encoding: 'utf8' }).trim().match(/[\d.]+/)?.[0] || ''; }
catch { /* not installed */ }

p.intro('tmux config builder');

if (!tmuxVersion) {
    p.log.error('tmux not found — brew install tmux (mac) / apt install tmux (linux)');
    p.outro('');
    process.exit(1);
}

p.log.success(`tmux ${tmuxVersion}`);
if (COPY_CMD) p.log.success(`clipboard: ${COPY_CMD.split(' ')[0]}`);
else p.log.warn('no clipboard tool found — clipboard features will be skipped');

const features = await p.multiselect({
    message: 'Select features',
    options: [
        { value: 'scrollback', label: 'Scrollback 100k', hint: 'default is 2,000 — Claude eats that fast' },
        { value: 'colors', label: 'True color + unicode', hint: 'full 16M colors + symbols ▶ ✓ ⚡' },
        { value: 'escape', label: 'No escape delay', hint: '0ms instead of 500ms — snappy vim' },
        { value: 'mouse', label: 'Mouse support', hint: 'click panes, scroll, drag to resize' },
        { value: 'splits', label: 'Intuitive splits', hint: '| and - instead of % and "' },
        { value: 'vimnav', label: 'Vim navigation', hint: 'h/j/k/l to move, H/J/K/L to resize' },
        { value: 'clipboard', label: 'System clipboard', hint: 'copy in tmux → Cmd+V works' },
        { value: 'statusbar', label: 'Minimal status bar', hint: 'session name + folder-labeled windows' },
        { value: 'autorename', label: 'Auto window names', hint: 'project, server, logs — not zsh, zsh, zsh' },
        { value: 'qol', label: 'Quality of life', hint: 'Ctrl+b r reload, no bells, renumber' },
    ],
    initialValues: ['scrollback', 'colors', 'escape', 'mouse', 'splits', 'vimnav', 'clipboard', 'statusbar', 'autorename', 'qol'],
    required: false,
});

if (p.isCancel(features)) { p.outro('cancelled'); process.exit(0); }

const has = (f) => features.includes(f);

// Sub-choice: mouse drag
let mouseHighlight = true;
if (has('mouse') && has('clipboard')) {
    const drag = await p.select({
        message: 'Mouse drag behavior',
        options: [
            { value: 'highlight', label: 'Highlight only', hint: 'press y to copy — prevents accidental overwrites' },
            { value: 'auto', label: 'Auto-copy on drag', hint: 'faster but can overwrite clipboard by accident' },
        ],
    });
    if (p.isCancel(drag)) { p.outro('cancelled'); process.exit(0); }
    mouseHighlight = drag === 'highlight';
}

// Build config
const lines = ['# Generated by tmux config builder', '# https://github.com/quickcall-dev/claude-config/tree/main/tmux', ''];

if (has('scrollback')) lines.push('set -g history-limit 100000', '');
if (has('colors')) lines.push('set -g default-terminal "tmux-256color"', 'set -ga terminal-overrides ",xterm-256color:Tc"', '');
if (has('escape')) lines.push('set -sg escape-time 0', '');
if (has('mouse')) lines.push('set -g mouse on', '');

if (has('splits')) {
    lines.push(
        'bind | split-window -h -c "#{pane_current_path}"',
        'bind - split-window -v -c "#{pane_current_path}"',
        'bind c new-window -c "#{pane_current_path}"',
        ''
    );
}

if (has('vimnav')) {
    lines.push(
        'bind h select-pane -L', 'bind j select-pane -D',
        'bind k select-pane -U', 'bind l select-pane -R',
        'bind -r H resize-pane -L 5', 'bind -r J resize-pane -D 5',
        'bind -r K resize-pane -U 5', 'bind -r L resize-pane -R 5',
        ''
    );
}

if (has('clipboard') && COPY_CMD) {
    lines.push(
        'setw -g mode-keys vi',
        `set -s copy-command '${COPY_CMD}'`,
        'bind -T copy-mode-vi v send -X begin-selection',
        'bind -T copy-mode-vi y send -X copy-selection-and-cancel',
        'bind -T copy-mode-vi Enter send -X copy-selection-and-cancel',
    );
    if (has('mouse')) {
        lines.push(mouseHighlight
            ? 'bind -T copy-mode-vi MouseDragEnd1Pane send -X cancel'
            : 'bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel'
        );
    }
    lines.push(`bind p run "${PASTE_CMD} | tmux load-buffer - && tmux paste-buffer"`, '');
}

if (has('statusbar')) {
    lines.push(
        'set -g status-interval 5', 'set -g status-position bottom',
        'set -g status-style bg=colour235,fg=colour248',
        'set -g status-left-length 30',
        'set -g status-left "#[fg=colour214,bold] #S #[fg=colour248]| "',
        'setw -g window-status-format " #I:#{b:pane_current_path} "',
        'setw -g window-status-current-format "#[fg=colour214,bold] #I:#{b:pane_current_path} "',
        ''
    );
}

if (has('autorename')) {
    lines.push(
        'set -g allow-rename on', 'setw -g automatic-rename on',
        "setw -g automatic-rename-format '#{b:pane_current_path}'",
        ''
    );
}

if (has('qol')) {
    lines.push(
        'bind r source-file ~/.tmux.conf \\; display "Config reloaded!"',
        'bind S new-session', 'set -g renumber-windows on',
        'set -g visual-activity off', 'set -g visual-bell off',
        'set -g visual-silence off', 'setw -g monitor-activity off',
        'set -g bell-action none', 'set -g focus-events on',
        ''
    );
}

const conf = lines.join('\n');

p.log.step(`${features.length}/10 features selected`);

// Install
let dest = DEST;

if (existsSync(DEST)) {
    const action = await p.select({
        message: '~/.tmux.conf already exists',
        options: [
            { value: 'replace', label: 'Replace', hint: 'backs up current config' },
            { value: 'side', label: 'Save as .tmux.conf.claude', hint: 'try before switching' },
            { value: 'cancel', label: 'Cancel' },
        ],
    });

    if (p.isCancel(action) || action === 'cancel') { p.outro('no changes'); process.exit(0); }

    if (action === 'replace') {
        const backup = `${DEST}.backup.${new Date().toISOString().replace(/[:.]/g, '').slice(0, 15)}`;
        copyFileSync(DEST, backup);
        writeFileSync(DEST, conf);
        p.log.success(`backup → ${backup}`);
        p.log.success(`installed → ${DEST}`);
    } else {
        dest = `${DEST}.claude`;
        writeFileSync(dest, conf);
        p.log.success(`saved → ${dest}`);
        p.log.info('try:  tmux source-file ~/.tmux.conf.claude');
        p.log.info('keep: mv ~/.tmux.conf.claude ~/.tmux.conf');
    }
} else {
    writeFileSync(DEST, conf);
    p.log.success(`installed → ${DEST}`);
}

// Reload if inside tmux
if (process.env.TMUX && dest === DEST) {
    try { execSync('tmux source-file ~/.tmux.conf', { stdio: 'ignore' }); p.log.success('reloaded'); }
    catch { /* ignore */ }
}

p.outro('Ctrl+b r to reload anytime');
